services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "y"
      MSSQL_SA_PASSWORD: "!Passw0rd"
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - sql_data:/var/opt/mssql

  server:
    build:
      context: .
      dockerfile: server/BookHub/dockerfile
    container_name: server
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BookHub;User Id=sa;Password=!Passw0rd;TrustServerCertificate=True;
      - Admin__Password=admin1234
      - Admin__Email=admin@mail.com
      - ApplicationSettings__Secret=A_very_strong_secret_key_that_is_at_least_16_characters_long
    networks:
      - backend

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    environment:
      - VITE_REACT_APP_SERVER_URL=http://localhost:8080
    networks:
      - backend
    depends_on:
      - server

networks:
  backend:
    driver: bridge

volumes:
  sql_data:
