FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080 8081

RUN useradd -m appuser
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["server/BookHub/BookHub.csproj", "server/BookHub/"]
RUN dotnet restore "server/BookHub/BookHub.csproj"

COPY server/ server/

WORKDIR "/src/server/BookHub"
RUN dotnet publish "BookHub.csproj" -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

USER appuser
ENTRYPOINT ["dotnet", "BookHub.dll"]
