export const baseUrl = import.meta?.env?.VITE_REACT_APP_SERVER_URL ?? 'http://localhost:8080';
export const baseAdminUrl = baseUrl + '/administrator';

export const routes = {
  home: '/',
  legal: {
    terms: '/terms',
    privacy: '/privacy',
    cookies: '/cookies',
  },
  readingChallenges: {
    base: '/readingChallenges',
    streak: '/readingChallenges/streak',
    checkIn: '/readingChallenges/check-in',
    progress: (year: number) => `/readingChallenges/${year}/progress`,
  },
  articles: '/articles',
  register: '/identity/register',
  login: '/identity/login',
  logout: '/identity/logout',
  statistics: '/statistics',
  profile: '/profile',
  mineProfile: '/profile/mine',
  profiles: '/profiles',
  topProfiles: '/profile/top',
  editProfile: '/profile/edit',
  book: '/books',
  booksByGenre: '/books/genre',
  booksByAuthor: '/books/author',
  topThreeBooks: '/books/top',
  createBook: '/books/new',
  editBook: '/books/edit',
  genres: '/genres',
  author: '/authors',
  topThreeAuthors: '/authors/top',
  createAuthor: '/authors/new',
  editAuthor: '/authors/edit',
  authorNames: '/authors/names',
  searchBooks: '/search/books',
  searchGenres: '/search/genres',
  searchArticles: '/search/articles',
  searchAuthors: '/search/authors',
  searchProfiles: '/search/profiles',
  searchChats: '/search/chats',
  review: '/reviews',
  vote: '/votes',
  badRequest: '/error/bad-request',
  notFound: '/error/not-found',
  accessDenied: '/access-denied',
  readingList: '/readingLists',
  lastCurrentlyReading: '/readingLists/last-currently-reading',
  notification: '/notifications',
  lastThreeNotifications: '/notifications/last',
  markNotificationRead: '/notifications/markAsRead',
  chat: '/chat',
  createChat: '/chat/new',
  editChat: '/chat/edit',
  chatsNotJoined: '/chat/not-joined',
  chatMessage: '/chatMessage',
  chatMessages: '/chat/messages',
  acceptChatInvitation: '/chat/invite/accept',
  rejectChatInvitation: '/chat/invite/reject',
  removeChatUser: '/chat/remove/user',
  admin: {
    book: '/admin/books',
    author: '/admin/authors',
    createArticle: '/admin/articles/new',
    editArticle: '/admin/articles/edit',
    approveBook: '/books/approve',
    rejectBook: '/books/reject',
    approveAuthor: '/authors/approve',
    rejectAuthor: '/authors/reject',
  },
};
