export const baseUrl = import.meta?.env?.VITE_REACT_APP_SERVER_URL ?? 'http://localhost:8080';
export const baseAdminUrl = baseUrl + '/administrator';

export const routes = {
  home: '/',
  articles: '/articles',
  register: '/identity/register',
  login: '/identity/login',
  logout: '/identity/logout',
  statistics: '/statistics',
  profile: '/profile',
  mineProfile: '/profile/mine',
  profiles: '/profiles',
  topProfiles: '/profile/top',
  editProfile: '/profile/edit',
  book: '/books',
  booksByGenre: '/books/genre',
  booksByAuthor: '/books/author',
  topThreeBooks: '/books/top',
  createBook: '/books/new',
  editBook: '/books/edit',
  genres: '/genres',
  author: '/author',
  topThreeAuthors: '/author/top',
  createAuthor: '/author/new',
  editAuthor: '/author/edit',
  authorNames: '/author/names',
  searchBooks: '/search/books',
  searchGenres: '/search/genres',
  searchArticles: '/search/articles',
  searchAuthors: '/search/authors',
  searchProfiles: '/search/profiles',
  searchChats: '/search/chats',
  review: '/reviews',
  vote: '/votes',
  badRequest: '/error/bad-request',
  notFound: '/error/not-found',
  accessDenied: '/access-denied',
  readingList: '/readingList',
  notification: '/notifications',
  lastThreeNotifications: '/notifications/last',
  markNotificationRead: '/notifications/markAsRead',
  chat: '/chat',
  chats: '/chats',
  createChat: '/chat/new',
  editChat: '/chat/edit',
  chatsNotJoined: '/chat/not-joined',
  chatMessage: '/chatMessage',
  acceptChatInvitation: '/chat/invite/accept',
  rejectChatInvitation: '/chat/invite/reject',
  removeChatUser: '/chat/remove/user',
  admin: {
    createArticle: '/admin/article/new',
    editArticle: '/admin/article/edit',
    approveBook: '/book/approve',
    rejectBook: '/book/reject',
    approveAuthor: '/author/approve',
    rejectAuthor: '/author/reject',
  },
};
